language: python

jobs:
  
  include:

    - name: "Tests + Coverage (Python 3.6)"
      stage: Test
      python: "3.6"
      install:
        - pip install -r requirements.txt
      script:
        - pytest -ra --cov=.

    - name: "Lint: black (Python 3.6)"
      python: "3.6"
      install:
        - pip install black
      script:
        - black --check --diff .

    - name: "Lint: flake8 (Python 3.6)"
      python: "3.6"
      install:
        - pip install flake8
      script:
        - flake8 --isolated --ignore=T484,T499,W503,E704,E231,E203 --max-line-length=127

stages:
  - name: Test

after_success:
  - codecov